use crate::parsed_class::SideOrder;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum UtilityGroup {
    Unknown,
    Container,
    Prose,
    SrOnly,
    NotSrOnly,
    ForcedColorAdjust,
    Appearance,
    Static,
    Fixed,
    Absolute,
    Relative,
    Sticky,
    Inset,
    InsetX,
    InsetY,
    Top,
    Right,
    Bottom,
    Left,
    Z,
    Isolate,
    Isolation,
    Block,
    Inline,
    InlineBlock,
    InlineFlex,
    Flex,
    InlineGrid,
    Grid,
    FlowRoot,
    Contents,
    Table,
    Hidden,
    Overflow,
    OverflowX,
    OverflowY,
    Overscroll,
    OverscrollX,
    OverscrollY,
    FlexBasis,
    FlexDirection,
    FlexWrap,
    FlexGrow,
    FlexShrink,
    Justify,
    JustifyItems,
    JustifySelf,
    Content,
    Items,
    AlignSelf,
    PlaceContent,
    PlaceItems,
    PlaceSelf,
    GridTemplate,
    GridCols,
    GridRows,
    GridAuto,
    Gap,
    GapX,
    GapY,
    Col,
    ColStart,
    ColEnd,
    Row,
    RowStart,
    RowEnd,
    AutoCols,
    AutoRows,
    Order,
    W,
    MinW,
    MaxW,
    H,
    MinH,
    MaxH,
    Size,
    P,
    Px,
    Py,
    Pt,
    Pr,
    Pb,
    Pl,
    M,
    Mx,
    My,
    Mt,
    Mr,
    Mb,
    Ml,
    SpaceX,
    SpaceY,
    Font,
    Text,
    Tracking,
    Leading,
    Whitespace,
    Break,
    List,
    Decoration,
    Uppercase,
    Lowercase,
    Capitalize,
    NormalCase,
    Truncate,
    TextEllipsis,
    TextClip,
    Align,
    Indent,
    VerticalAlign,
    WordBreak,
    Hyphens,
    Bg,
    GradientFrom,
    GradientVia,
    GradientTo,
    Border,
    BorderX,
    BorderY,
    BorderT,
    BorderR,
    BorderB,
    BorderL,
    Outline,
    Ring,
    RingOffset,
    Divide,
    DivideX,
    DivideY,
    Rounded,
    RoundedT,
    RoundedR,
    RoundedB,
    RoundedL,
    RoundedTl,
    RoundedTr,
    RoundedBr,
    RoundedBl,
    Opacity,
    Shadow,
    BoxShadow,
    DropShadow,
    Blur,
    BackdropBlur,
    MixBlend,
    BgBlend,
    Filter,
    Brightness,
    Contrast,
    Grayscale,
    HueRotate,
    Invert,
    Saturate,
    Sepia,
    BackdropFilter,
    BackdropBrightness,
    BackdropContrast,
    BackdropGrayscale,
    BackdropHueRotate,
    BackdropInvert,
    BackdropSaturate,
    BackdropSepia,
    TableLayout,
    BorderCollapse,
    BorderSpacing,
    CaptionSide,
    Transition,
    Animate,
    Ease,
    Duration,
    Delay,
    Transform,
    TransformOrigin,
    Scale,
    ScaleX,
    ScaleY,
    Rotate,
    RotateX,
    RotateY,
    RotateZ,
    Translate,
    TranslateX,
    TranslateY,
    Skew,
    SkewX,
    SkewY,
    Cursor,
    PointerEvents,
    Resize,
    UserSelect,
    Scroll,
    Scrollbar,
    Accent,
    Caret,
    Touch,
    WillChange,
    Fill,
    Stroke,
    StrokeWidth,
    ArbitraryProperty,
    Custom,
}

pub fn classify_utility(base: &str) -> UtilityGroup {
    match base {
        "container" => UtilityGroup::Container,
        "prose" => UtilityGroup::Prose,
        "sr-only" | "sr_only" => UtilityGroup::SrOnly,
        "not-sr-only" | "not_sr_only" => UtilityGroup::NotSrOnly,
        "forced-color-adjust" | "forced_color_adjust" => UtilityGroup::ForcedColorAdjust,
        "appearance" => UtilityGroup::Appearance,
        "static" => UtilityGroup::Static,
        "fixed" => UtilityGroup::Fixed,
        "absolute" => UtilityGroup::Absolute,
        "relative" => UtilityGroup::Relative,
        "sticky" => UtilityGroup::Sticky,
        "inset" => UtilityGroup::Inset,
        "inset-x" | "inset_x" => UtilityGroup::InsetX,
        "inset-y" | "inset_y" => UtilityGroup::InsetY,
        "top" => UtilityGroup::Top,
        "right" => UtilityGroup::Right,
        "bottom" => UtilityGroup::Bottom,
        "left" => UtilityGroup::Left,
        "z" => UtilityGroup::Z,
        "isolate" => UtilityGroup::Isolate,
        "isolation" => UtilityGroup::Isolation,
        "block" => UtilityGroup::Block,
        "inline" => UtilityGroup::Inline,
        "inline-block" | "inline_block" => UtilityGroup::InlineBlock,
        "inline-flex" | "inline_flex" => UtilityGroup::InlineFlex,
        "flex" => UtilityGroup::Flex,
        "inline-grid" | "inline_grid" => UtilityGroup::InlineGrid,
        "grid" => UtilityGroup::Grid,
        "flow-root" | "flow_root" => UtilityGroup::FlowRoot,
        "contents" => UtilityGroup::Contents,
        "table" => UtilityGroup::Table,
        "hidden" => UtilityGroup::Hidden,
        "overflow" => UtilityGroup::Overflow,
        "overflow-x" | "overflow_x" => UtilityGroup::OverflowX,
        "overflow-y" | "overflow_y" => UtilityGroup::OverflowY,
        "overscroll" => UtilityGroup::Overscroll,
        "overscroll-x" | "overscroll_x" => UtilityGroup::OverscrollX,
        "overscroll-y" | "overscroll_y" => UtilityGroup::OverscrollY,
        "basis" | "flex-basis" | "flex_basis" => UtilityGroup::FlexBasis,
        "flex-row" | "flex_row" | "flex-col" | "flex_col" | "flex-direction" | "flex_direction" | "direction" => {
            UtilityGroup::FlexDirection
        }
        "flex-wrap" | "flex_wrap" | "wrap" => UtilityGroup::FlexWrap,
        "flex-grow" | "flex_grow" | "grow" => UtilityGroup::FlexGrow,
        "flex-shrink" | "flex_shrink" | "shrink" => UtilityGroup::FlexShrink,
        "justify" => UtilityGroup::Justify,
        "justify-items" | "justify_items" => UtilityGroup::JustifyItems,
        "justify-self" | "justify_self" => UtilityGroup::JustifySelf,
        "content" => UtilityGroup::Content,
        "items" => UtilityGroup::Items,
        "self" => UtilityGroup::AlignSelf,
        "place-content" | "place_content" => UtilityGroup::PlaceContent,
        "place-items" | "place_items" => UtilityGroup::PlaceItems,
        "place-self" | "place_self" => UtilityGroup::PlaceSelf,
        "grid-template" | "grid_template" => {
            UtilityGroup::GridTemplate
        }
        "grid-cols" | "grid_cols" | "grid-template-columns" | "grid_template_columns" => UtilityGroup::GridCols,
        "grid-rows" | "grid_rows" | "grid-template-rows" | "grid_template_rows" => UtilityGroup::GridRows,
        "grid-auto" | "grid_auto" | "auto" => UtilityGroup::GridAuto,
        "gap" => UtilityGroup::Gap,
        "gap-x" | "gap_x" => UtilityGroup::GapX,
        "gap-y" | "gap_y" => UtilityGroup::GapY,
        "col" => UtilityGroup::Col,
        "col-start" | "col_start" => UtilityGroup::ColStart,
        "col-end" | "col_end" => UtilityGroup::ColEnd,
        "row" => UtilityGroup::Row,
        "row-start" | "row_start" => UtilityGroup::RowStart,
        "row-end" | "row_end" => UtilityGroup::RowEnd,
        "auto-cols" | "auto_cols" => UtilityGroup::AutoCols,
        "auto-rows" | "auto_rows" => UtilityGroup::AutoRows,
        "order" => UtilityGroup::Order,
        "w" => UtilityGroup::W,
        "min-w" | "min_w" => UtilityGroup::MinW,
        "max-w" | "max_w" => UtilityGroup::MaxW,
        "h" => UtilityGroup::H,
        "min-h" | "min_h" => UtilityGroup::MinH,
        "max-h" | "max_h" => UtilityGroup::MaxH,
        "size" => UtilityGroup::Size,
        "p" => UtilityGroup::P,
        "px" => UtilityGroup::Px,
        "py" => UtilityGroup::Py,
        "pt" => UtilityGroup::Pt,
        "pr" => UtilityGroup::Pr,
        "pb" => UtilityGroup::Pb,
        "pl" => UtilityGroup::Pl,
        "m" => UtilityGroup::M,
        "mx" => UtilityGroup::Mx,
        "my" => UtilityGroup::My,
        "mt" => UtilityGroup::Mt,
        "mr" => UtilityGroup::Mr,
        "mb" => UtilityGroup::Mb,
        "ml" => UtilityGroup::Ml,
        "space-x" | "space_x" => UtilityGroup::SpaceX,
        "space-y" | "space_y" => UtilityGroup::SpaceY,
        "font" => UtilityGroup::Font,
        "text" => UtilityGroup::Text,
        "tracking" => UtilityGroup::Tracking,
        "leading" => UtilityGroup::Leading,
        "whitespace" => UtilityGroup::Whitespace,
        "break" => UtilityGroup::Break,
        "list" => UtilityGroup::List,
        "decoration" => UtilityGroup::Decoration,
        "uppercase" => UtilityGroup::Uppercase,
        "lowercase" => UtilityGroup::Lowercase,
        "capitalize" => UtilityGroup::Capitalize,
        "normal-case" | "normal_case" => UtilityGroup::NormalCase,
        "truncate" => UtilityGroup::Truncate,
        "text-ellipsis" | "text_ellipsis" => UtilityGroup::TextEllipsis,
        "text-clip" | "text_clip" => UtilityGroup::TextClip,
        "align" => UtilityGroup::Align,
        "indent" => UtilityGroup::Indent,
        "vertical-align" | "vertical_align" => UtilityGroup::VerticalAlign,
        "word-break" | "word_break" => UtilityGroup::WordBreak,
        "hyphens" => UtilityGroup::Hyphens,
        "bg" => UtilityGroup::Bg,
        "from" => UtilityGroup::GradientFrom,
        "via" => UtilityGroup::GradientVia,
        "to" => UtilityGroup::GradientTo,
        "border" => UtilityGroup::Border,
        "border-x" | "border_x" => UtilityGroup::BorderX,
        "border-y" | "border_y" => UtilityGroup::BorderY,
        "border-t" | "border_t" => UtilityGroup::BorderT,
        "border-r" | "border_r" => UtilityGroup::BorderR,
        "border-b" | "border_b" => UtilityGroup::BorderB,
        "border-l" | "border_l" => UtilityGroup::BorderL,
        "outline" => UtilityGroup::Outline,
        "ring" => UtilityGroup::Ring,
        "ring-offset" | "ring_offset" => UtilityGroup::RingOffset,
        "divide" => UtilityGroup::Divide,
        "divide-x" | "divide_x" => UtilityGroup::DivideX,
        "divide-y" | "divide_y" => UtilityGroup::DivideY,
        "rounded" => UtilityGroup::Rounded,
        "rounded-t" | "rounded_t" => UtilityGroup::RoundedT,
        "rounded-r" | "rounded_r" => UtilityGroup::RoundedR,
        "rounded-b" | "rounded_b" => UtilityGroup::RoundedB,
        "rounded-l" | "rounded_l" => UtilityGroup::RoundedL,
        "rounded-tl" | "rounded_tl" => UtilityGroup::RoundedTl,
        "rounded-tr" | "rounded_tr" => UtilityGroup::RoundedTr,
        "rounded-br" | "rounded_br" => UtilityGroup::RoundedBr,
        "rounded-bl" | "rounded_bl" => UtilityGroup::RoundedBl,
        "opacity" => UtilityGroup::Opacity,
        "shadow" => UtilityGroup::Shadow,
        "box-shadow" | "box_shadow" => UtilityGroup::BoxShadow,
        "drop-shadow" | "drop_shadow" => UtilityGroup::DropShadow,
        "blur" => UtilityGroup::Blur,
        "backdrop-blur" | "backdrop_blur" => UtilityGroup::BackdropBlur,
        "mix-blend" | "mix_blend" => UtilityGroup::MixBlend,
        "bg-blend" | "bg_blend" => UtilityGroup::BgBlend,
        "filter" => UtilityGroup::Filter,
        "brightness" => UtilityGroup::Brightness,
        "contrast" => UtilityGroup::Contrast,
        "grayscale" => UtilityGroup::Grayscale,
        "hue-rotate" | "hue_rotate" => UtilityGroup::HueRotate,
        "invert" => UtilityGroup::Invert,
        "saturate" => UtilityGroup::Saturate,
        "sepia" => UtilityGroup::Sepia,
        "backdrop-filter" | "backdrop_filter" => UtilityGroup::BackdropFilter,
        "backdrop-brightness" | "backdrop_brightness" => UtilityGroup::BackdropBrightness,
        "backdrop-contrast" | "backdrop_contrast" => UtilityGroup::BackdropContrast,
        "backdrop-grayscale" | "backdrop_grayscale" => UtilityGroup::BackdropGrayscale,
        "backdrop-hue-rotate" | "backdrop_hue_rotate" => UtilityGroup::BackdropHueRotate,
        "backdrop-invert" | "backdrop_invert" => UtilityGroup::BackdropInvert,
        "backdrop-saturate" | "backdrop_saturate" => UtilityGroup::BackdropSaturate,
        "backdrop-sepia" | "backdrop_sepia" => UtilityGroup::BackdropSepia,
        "table-layout" | "table_layout" => UtilityGroup::TableLayout,
        "border-collapse" | "border_collapse" => UtilityGroup::BorderCollapse,
        "border-spacing" | "border_spacing" => UtilityGroup::BorderSpacing,
        "caption-side" | "caption_side" => UtilityGroup::CaptionSide,
        "transition" => UtilityGroup::Transition,
        "animate" => UtilityGroup::Animate,
        "ease" => UtilityGroup::Ease,
        "duration" => UtilityGroup::Duration,
        "delay" => UtilityGroup::Delay,
        "transform" => UtilityGroup::Transform,
        "transform-origin" | "transform_origin" | "origin" => UtilityGroup::TransformOrigin,
        "scale" => UtilityGroup::Scale,
        "scale-x" | "scale_x" => UtilityGroup::ScaleX,
        "scale-y" | "scale_y" => UtilityGroup::ScaleY,
        "rotate" => UtilityGroup::Rotate,
        "rotate-x" | "rotate_x" => UtilityGroup::RotateX,
        "rotate-y" | "rotate_y" => UtilityGroup::RotateY,
        "rotate-z" | "rotate_z" => UtilityGroup::RotateZ,
        "translate" => UtilityGroup::Translate,
        "translate-x" | "translate_x" => UtilityGroup::TranslateX,
        "translate-y" | "translate_y" => UtilityGroup::TranslateY,
        "skew" => UtilityGroup::Skew,
        "skew-x" | "skew_x" => UtilityGroup::SkewX,
        "skew-y" | "skew_y" => UtilityGroup::SkewY,
        "cursor" => UtilityGroup::Cursor,
        "pointer-events" | "pointer_events" => UtilityGroup::PointerEvents,
        "resize" => UtilityGroup::Resize,
        "user-select" | "user_select" | "select" => UtilityGroup::UserSelect,
        "scroll" => UtilityGroup::Scroll,
        "scrollbar" => UtilityGroup::Scrollbar,
        "accent" => UtilityGroup::Accent,
        "caret" => UtilityGroup::Caret,
        "touch" => UtilityGroup::Touch,
        "will-change" | "will_change" => UtilityGroup::WillChange,
        "fill" => UtilityGroup::Fill,
        "stroke" => UtilityGroup::Stroke,
        "stroke-width" | "stroke_width" => UtilityGroup::StrokeWidth,
        _ => UtilityGroup::Unknown,
    }
}

pub fn classify_override(base: &str) -> SideOrder {
    match base {
        "p" | "m" | "border" | "rounded" | "ring" | "outline" | "inset" | "z"
        | "scale" | "translate" | "skew" => SideOrder::Shorthand,
        "px" | "py" | "mx" | "my" | "border-x" | "border-y" | "gap-x" | "gap-y"
        | "rounded-t" | "rounded-b" | "rounded-l" | "rounded-r"
        | "space-x" | "space-y" | "scale-x" | "scale-y" | "translate-x" | "translate-y"
        | "skew-x" | "skew-y" | "overflow-x" | "overflow-y" | "overscroll-x"
        | "overscroll-y" | "divide-x" | "divide-y" | "inset-x" | "inset-y"
        | "min-w" | "min-h" | "max-w" | "max-h" => SideOrder::Axis,
        "pt" | "pr" | "pb" | "pl" | "mt" | "mr" | "mb" | "ml"
        | "border-t" | "border-r" | "border-b" | "border-l"
        | "rounded-tl" | "rounded-tr" | "rounded-br" | "rounded-bl"
        | "top" | "right" | "bottom" | "left" => SideOrder::Direction,
        _ => SideOrder::Shorthand,
    }
}

pub fn is_same_family(a: &str, b: &str) -> bool {
    let a_family = family_root(a);
    let b_family = family_root(b);
    a_family == b_family
}

fn family_root(base: &str) -> &str {
    match base {
        "pt" | "pr" | "pb" | "pl" | "px" | "py" | "p" => "p",
        "mt" | "mr" | "mb" | "ml" | "mx" | "my" | "m" => "m",
        "border-t" | "border_r" | "border-b" | "border-l" | "border-x" | "border-y" | "border" => "border",
        "rounded" | "rounded-t" | "rounded-r" | "rounded-b" | "rounded-l"
        | "rounded-tl" | "rounded_tr" | "rounded-br" | "rounded-bl" => "rounded",
        "inset" | "inset-x" | "inset-y" | "top" | "right" | "bottom" | "left" => "inset",
        "scale" | "scale-x" | "scale-y" => "scale",
        "translate" | "translate-x" | "translate-y" => "translate",
        "skew" | "skew-x" | "skew-y" => "skew",
        "ring" | "ring-offset" => "ring",
        "divide" | "divide-x" | "divide-y" => "divide",
        "min-w" | "min-h" | "max-w" | "max-h" | "w" | "h" | "size" => "sizing",
        "space-x" | "space-y" => "space",
        _ => base,
    }
}

pub fn classify_arbitrary_property(prop: &str) -> UtilityGroup {
    let prop = if let Some(close_idx) = prop.find(':') {
        &prop[..close_idx]
    } else {
        prop
    };

    match prop {
        "display" | "visibility" => UtilityGroup::Hidden,
        "position" => UtilityGroup::Static,
        "inset" | "top" | "right" | "bottom" | "left" => UtilityGroup::Inset,
        "z-index" => UtilityGroup::Z,
        "overflow" | "overflow-x" | "overflow-y" => UtilityGroup::Overflow,
        "flex" | "flex-basis" | "flex-direction" | "flex-wrap" | "flex-grow" | "flex-shrink" => {
            UtilityGroup::FlexBasis
        }
        "justify-content" | "justify-items" | "justify-self" => UtilityGroup::Justify,
        "align-items" | "align-content" | "align-self" => UtilityGroup::Items,
        "place-content" | "place-items" | "place-self" => UtilityGroup::PlaceContent,
        "grid-template" | "grid-template-columns" | "grid-template-rows" => UtilityGroup::GridTemplate,
        "gap" | "row-gap" | "column-gap" => UtilityGroup::Gap,
        "order" => UtilityGroup::Order,
        "width" | "min-width" | "max-width" | "w" => UtilityGroup::W,
        "height" | "min-height" | "max-height" | "h" => UtilityGroup::H,
        "padding" | "padding-top" | "padding-right" | "padding-bottom" | "padding-left" => UtilityGroup::P,
        "margin" | "margin-top" | "margin-right" | "margin-bottom" | "margin-left" => UtilityGroup::M,
        "font-family" | "font-size" | "font-weight" | "font-style" => UtilityGroup::Font,
        "text-align" | "text-decoration" | "text-transform" | "text-indent" | "text-shadow"
        | "text-overflow" | "letter-spacing" | "line-height" | "white-space" | "word-break"
        | "word-wrap" | "overflow-wrap" | "vertical-align" | "color" => UtilityGroup::Text,
        "background" | "background-color" | "background-image" | "background-position"
        | "background-size" | "background-repeat" | "background-attachment" | "background-clip" => {
            UtilityGroup::Bg
        }
        "border" | "border-top" | "border-right" | "border-bottom" | "border-left"
        | "border-width" | "border-style" | "border-color" | "border-radius"
        | "outline" | "outline-width" | "outline-style" | "outline-color"
        | "outline-offset" => UtilityGroup::Border,
        "opacity" | "box-shadow" | "filter" | "backdrop-filter" | "mix-blend-mode"
        | "background-blend-mode" | "blur" => UtilityGroup::Opacity,
        "transition" | "transition-property" | "transition-duration" | "transition-timing-function"
        | "transition-delay" | "animation" | "animation-name" | "animation-duration"
        | "animation-timing-function" | "animation-delay" | "animation-iteration-count"
        | "animation-direction" | "animation-fill-mode" | "animation-play-state" => {
            UtilityGroup::Transition
        }
        "transform" | "transform-origin" | "transform-style" | "perspective"
        | "perspective-origin" | "backface-visibility" => UtilityGroup::Transform,
        "cursor" | "pointer-events" | "user-select" | "resize" | "scroll-behavior"
        | "touch-action" | "will-change" => UtilityGroup::Cursor,
        "fill" | "stroke" | "stroke-width" | "stroke-dasharray" | "stroke-dashoffset"
        | "stroke-linecap" | "stroke-linejoin" | "stroke-miterlimit" | "stroke-opacity" => {
            UtilityGroup::Fill
        }
        "mask" | "mask-image" | "mask-size" | "mask-repeat" | "mask-position"
        | "mask-composite" | "mask-mode" | "mask-type" => UtilityGroup::Fill,
        _ => UtilityGroup::Unknown,
    }
}
